GENERATE_GENOMS = 250

ELITE_GENOMS = int(GENERATE_GENOMS * 0.2)
PROGENY_GENOMS = int(GENERATE_GENOMS * 0.4)
NORMAL_GENOMS = GENERATE_GENOMS - (ELITE_GENOMS + PROGENY_GENOMS)

GENE_MAX = 100
GENE_MUTATION = 100
GENOM_CROSSOVER = 100
GENOM_GENERATION = 100
